apiVersion: v1
kind: ReplicationController
metadata:
  name: example-mean-todo-db
  labels:
    app: example-mean-todo-db
spec:
  replicas: 1
  selector:
    app: example-mean-todo-db
    version: green
  template:
    metadata:
      labels:
        app: example-mean-todo-db
        version: green
    spec:
      containers:
      - name: example-mean-todo-db
        imagePullPolicy: Always
        image: 703587889398.dkr.ecr.us-east-1.amazonaws.com/example-mean-todo-db:base
        ports:
        - name: appport
          containerPort: 27017
